### ISSUE TITLE
High level design of quiz app

### ISSUE THREAD

**Issue by kadumuri1994** [UdacityFrontEndScholarship/quiz-app#10]
This would certainly help the developers/contributors understand the architecture of the web application (using a diagram) detailing the interaction of each component (using an underlying technology) of the product.
An example of such would be as below:
https://goo.gl/images/eCfxoT

**Comment by vattytrivedi** [comment]
# Suggestion in Look and feel

Great to see that the technology stack in the react. Just a suggestion have a look at the [Grommet](http://grommet.io/) it is much better and easy to integrate than Bootstrap, as it is built for react only.

**Comment by vattytrivedi** [comment]
Thanks for reply @lalitmee
