### ISSUE TITLE
Data Model for the app.

### ISSUE THREAD

**Issue by ezioda004** [UdacityFrontEndScholarship/quiz-app#2]
Come up with the data model for the app.
You should consider these features while working on it.

A Single Page Application which has:
1. Dashboard for separate users (Users can access their profile, see their previous challenge score etc)
2. A Player vs Player mode, where users can challenge random users.
3. A Practice mode, where users will be tested with their preferred language against the greatest enemy of all- time itself.
4. A leader-board system where users can see who has won the most challenges and has the most experience in the progression system.

**Comment by ezioda004** [comment]
Assigning it to @kadumuri1994

**Comment by kadumuri1994** [comment]
![challenge page](https://user-images.githubusercontent.com/36915315/38571431-1e4ff09e-3d0e-11e8-80ee-8d846e478889.jpg)
In the player vs player mode, as the per the design by parul, I see a question with 4 options and a timer. May I know how does it work? I understand their can be two ways of implementing it.
1. Whoever answers first, his score will be increase and next question will be displayed.
2. Both of them can answer the question before timers goes to zero. In this case, scores of any player increases if he answers rightly
How it is supposed to be?

**Comment by kadumuri1994** [comment]
Tried making a data model. Please access it at the below link by signing up (You can view and edit):

https://www.lucidchart.com/invitations/accept/4959f428-f905-44ff-9a82-1cd55f6cf960

I think there needs to be lot more modifications to this. Review this and give feedback .

**Comment by jibin2706** [comment]
@kadumuri1994 
For both players to play simultaneously means the number of people using this app should large. Instead we can take a other approach maybe.
Like the first player can answer and when ever the second player comes online he could answer.
Just a suggestion.

**Comment by Vanisha27** [comment]
Hey @jibin2706 
Actually, it's a challenge mode, kinda like inviting someone to play pool or cards online. So both players need to be online and taking the quiz.

**Comment by ezioda004** [comment]
@jibin2706 This is exactly the approach we're taking. I reckon this will give us more flexibility with the implementation. Thanks for your suggestion!

**Comment by ezioda004** [comment]
@sumilmehta It's more or less high level model so some attributes wont match up exactly. I won't really fret about this.
Closing this.
