### ISSUE TITLE
Create a Navbar for Signup/Signin Page

### ISSUE THREAD

**Issue by ezioda004** [UdacityFrontEndScholarship/quiz-app#23]
Create a navbar as shown in [this picture](https://raw.githubusercontent.com/parulbindal/quiz-app/master/src/assets/images/Sign%20Up%20Page%20Detailed.jpg)

How to get started? Read our [project setup instructions](https://github.com/UdacityFrontEndScholarship/quiz-app/blob/master/CONTRIBUTING.md#project-setup-instructions).
Fork the project, navigate to directory quiz-app => src => Component => Header.js

All you need to do is write HTML inside the `<header> </header>` element.

Note: 
1. If you use any self closing tags such as `<img>`, `<input>`, `<br>`
Make sure you always close them like this `<img />`, `<input />`, `<br />`

2. If you add a `class` to an element example 
```
<div  class = "nav navbar"> 
    <!-- rest of your code -->
</div>
```
Make sure you use **className** instead of **class**. Example

```
<div  className = "nav navbar"> 
    <!-- rest of your code -->
</div>
```

**You only need to create the elements, please don't style them yet.** I'll create different issue for that after this one is resolved.

This is fairly easy and straightforward to do, please comment on this issue and I'll assign it to you.

**Comment by lalitmee** [comment]
Yeah sure, @abhishekakade. 
Assigned to you.

**Comment by abhishekakade** [comment]
Thanks! :raised_hands:t4:

**Comment by Amir22010** [comment]
can i do that, + routing too

**Comment by ezioda004** [comment]
@Amir22010 We've assigned this to @abhishekakade 
We'll be making more issues (for routing too), everyone will get a chance.

**Comment by abhishekakade** [comment]
@ezioda004 done. Please check PR and suggest changes if any. Thanks! :raised_hands:

**Comment by ezioda004** [comment]
Resolved by @abhishekakade 
Closing this issue.
