### ISSUE TITLE
Create a SignUp form for Signup/Signin Page

### ISSUE THREAD

**Issue by ezioda004** [UdacityFrontEndScholarship/quiz-app#24]
Create a Signup form as shown in [this picture](https://raw.githubusercontent.com/parulbindal/quiz-app/master/src/assets/images/Sign%20Up%20Page%20Detailed.jpg)

How to get started? Read our [project setup instructions](https://github.com/UdacityFrontEndScholarship/quiz-app/blob/master/CONTRIBUTING.md#project-setup-instructions).
Fork the project, navigate to directory quiz-app => src => Component => Signup.js

All you need to do is write HTML inside the `<main> </main>` element.

Note: 
1. If you use any self closing tags such as `<img>`, `<input>`, `<br>`
Make sure you always close them like this `<img />`, `<input />`, `<br />`

2. If you add a `class` to an element example 
```
<div  class = "nav navbar"> 
    <!-- rest of your code -->
</div>
```
Make sure you use **className** instead of **class**. Example

```
<div  className = "nav navbar"> 
    <!-- rest of your code -->
</div>
```

**You only need to create the elements, please don't style them yet.** I'll create different issue for that after this one is resolved.

This is fairly easy and straightforward to do, please comment on this issue and I'll assign it to you.

**Comment by suhas023** [comment]
I'll work on this.

**Comment by lalitmee** [comment]
assigned to @suhas023. :+1:

**Comment by ezioda004** [comment]
Resolved by @suhas023 
Closing.
