### ISSUE TITLE
Create a SignIn form for Signup/Signin Page

### ISSUE THREAD

**Issue by ezioda004** [UdacityFrontEndScholarship/quiz-app#25]
Create a Signin form as shown in [this picture](https://raw.githubusercontent.com/parulbindal/quiz-app/master/src/assets/images/Sign%20In%20Page%20Detailed.jpg)

How to get started? Read our [project setup instructions](https://github.com/UdacityFrontEndScholarship/quiz-app/blob/master/CONTRIBUTING.md#project-setup-instructions).
Fork the project, navigate to directory quiz-app => src => Component => Signin.js

All you need to do is write HTML inside the `<main> </main>` element.

Note: 
1. If you use any self closing tags such as `<img>`, `<input>`, `<br>`
Make sure you always close them like this `<img />`, `<input />`, `<br />`

2. If you add a `class` to an element example 
```
<div  class = "nav navbar"> 
    <!-- rest of your code -->
</div>
```
Make sure you use **className** instead of **class**. Example

```
<div  className = "nav navbar"> 
    <!-- rest of your code -->
</div>
```

**You only need to create the elements, please don't style them yet.** I'll create different issue for that after this one is resolved.

Don't worry about authentication, you only need to create buttons. We'll do the rest!

This is fairly easy and straightforward to do, please comment on this issue and I'll assign it to you.

**Comment by abhishekakade** [comment]
Can I work on this one?

**Comment by lalitmee** [comment]
hey @abhishekakade, I have assinged you the other issue. First complete that then will assgin you to this issue. :wink:

**Comment by ezioda004** [comment]
What @lalitmee said, we'd like more first times to tackle this issue.

**Comment by Ajayjam97** [comment]
Can i work on this?

**Comment by ezioda004** [comment]
@Ajayjam97 Absolutely, assigned to you. If you have any issues feel free to contact us.

**Comment by Ajayjam97** [comment]
Thanks! @ezioda004.
As we only have to create elements so I have created this signIn form.  It does not contain any style. I am attaching the image of my result. Is this good or I should improve it further?

![signin](https://user-images.githubusercontent.com/21179880/38765395-1283d26c-3fde-11e8-92a5-83fda7fe184a.PNG)

**Comment by ezioda004** [comment]
@Ajayjam97 That's fine for now, however you can add SVG icons for Google and Github. I'd suggest using this. http://konpa.github.io/devicon/ I'm sure you can find the exact icon as shown in the picture.

**Comment by abhishekakade** [comment]
Sure! :) @ezioda004, @lalitmee

**Comment by ezioda004** [comment]
Resolved by @Ajayjam97 
Closing this issue.
