### ISSUE TITLE
In Header collapse navbar not working

### ISSUE THREAD

**Issue by jibin2706** [UdacityFrontEndScholarship/quiz-app#35]
I think we have to include bootstrap.js and jQuery

**Comment by ezioda004** [comment]
Hi, @jibin2706,
Thank you for bringing this to our attention.
We've added that as a dependency but apparently its still not working even with importing.
I'd look into that, meanwhile can you make a PR with latest jQuery CDN and popper.js CDN added in the `index.html` file?

**Comment by jibin2706** [comment]
yes sure

**Comment by ezioda004** [comment]
Resolved with #36 
Closing.
