### ISSUE TITLE
Make a contributing guide.

### ISSUE THREAD

**Issue by ezioda004** [UdacityFrontEndScholarship/quiz-app#4]
Make a guide for users to get started with React and a contributing guide.

**Comment by lalitmee** [comment]
@ezioda004 I think we can remove the default `Readme.md` file from our project and create a new one for the same. 
I can make a contributing guide that will help us in reviewing the code and commits very easily. I have seen a standard one in [coala](https://github.com/coala/coala) organization. They have a very good contributing guide.

**Comment by ezioda004** [comment]
@fayazara You can work on semantics/workflow guide.
@lalitmee Yes, the default README.md is only temporary. It does have some troubleshooting methods, You can work on making a guide for React/Contribution (leave the setup part of the project).

Assigning this task to both of you.

We'll need a setup guide(github quick-guide) for the project, which I'll let a beginner make. It'll be their good first contribution.

**Comment by lalitmee** [comment]
Hey @ezioda004, actually I would say that don't call them beginners :wink: 
you can call other team members if you want to refer. 
Now we are a team no one is beginner and expert. We all are here for learning something new. :innocent:

**Comment by ezioda004** [comment]
@lalitmee The peers who have been learning web-dev for only past couple of months, I'd say they're just beginning their journey therefore a beginner. Team-member would be inaccurate term because the team here is well "us". We're suppose to guide them, anyway this is going off-topic and can be discussed somewhere else. 

Please keep the comments here clean and on topic with the issue.
