### ISSUE TITLE
Change the color of Active and Inactive Tab of Forms

### ISSUE THREAD

**Issue by lalitmee** [UdacityFrontEndScholarship/quiz-app#45]
The color of the active tab of the SignUp Form and SignIn Form should be same as it is in this [figure](https://raw.githubusercontent.com/parulbindal/quiz-app/master/src/assets/images/Sign%20Up%20Page%20Detailed.jpg). 

The border around the inputs should be not this much dark black. I think this `#c4c8cc` color value will be good for border color of all the inputs in the forms.

**Comment by Ajayjam97** [comment]
Can i do it?

**Comment by ezioda004** [comment]
I'm aware of the active tab issue and was working on that so to speak since it requires React and a bit more understanding I was avoiding any beginners to work on it.
@Ajayjam97 You can work on the input border if you want.

**Comment by Ajayjam97** [comment]
@ezioda004  Yes! sure. But If the active tab issue is not created as a new one, can i give it a try?

**Comment by ezioda004** [comment]
@pben1984 Both, but mainly a React logic.

@Ajayjam97 Well, I also have to clean up and refactor some of the Component logic, another reason why I was avoiding anyone to work on it. 
Do not worry we will make more React specific issues.
Meanwhile, I'm assigning the latter task (inputs border) issue to you.

**Comment by Ajayjam97** [comment]
Ok! I understand. 👍

**Comment by Ajayjam97** [comment]
@lalitmee I have styled all the borders with red for my doubt. Should I add #c4c8cc color to all of them or just the input boxes?

![input](https://user-images.githubusercontent.com/21179880/38826603-f3ceec34-41cd-11e8-9d88-217c048f75ab.PNG)

**Comment by lalitmee** [comment]
only input boxes, :wink:

**Comment by lalitmee** [comment]
border color of these `Sign Up with Google` and `Sign Up with Github` also should be the same as input boxes.

**Comment by Ajayjam97** [comment]
ok 👍

**Comment by abhishekakade** [comment]
@shubhsurya06 by default those buttons do have a border radius but as the UI/theme demanded, I changed the border radius to 0. But its a small issue, if they feel like they want border radius it can be added any time :sweat_smile:

**Comment by shubhsurya06** [comment]
If its already discussed, then it's ok.

**Comment by ezioda004** [comment]
@shubhsurya06 We'll be adding enhancements issues if required or you can open one yourself have a discussion going on about it. :)

**Comment by ezioda004** [comment]
Resolved as per #47 and #49 
Closing.
