### ISSUE TITLE
Create a Navbar and Style it for Welcome Page

### ISSUE THREAD

**Issue by ezioda004** [UdacityFrontEndScholarship/quiz-app#52]
## Create a Navbar and Style it as shown in below

![image](https://user-images.githubusercontent.com/20020273/39008887-a33dcf54-4427-11e8-98a6-fde344642338.png)

Here's the [logo](https://raw.githubusercontent.com/parulbindal/quiz-app/master/src/assets/images/skillup%20logo.jpg)

How to get started? Read our [project setup instructions](https://github.com/UdacityFrontEndScholarship/quiz-app/blob/master/CONTRIBUTING.md#project-setup-instructions).
Fork the project, navigate to directory quiz-app => src => Component => Navbar => Navbar.js and Navbar.css

All you need to do is write HTML inside the `<nav> </nav>` element and style inside Navbar.css
We're using Bootstrap4 for this project but feel free to use native CSS wherever you require.

Note: 
1. If you use any self closing tags such as `<img>`, `<input>`, `<br>`
Make sure you always close them like this `<img />`, `<input />`, `<br />`

2.  **DO NOT TOUCH `<Link>`**:
This element is responsible for seamless routing without backend, if you want to work with it. Think of it as `<a href = ""> </a>`. If you want to add a class to it you can do
```
<Link className = "whatever-class"> </Link>
```

3. If you add a `class` to an element example 
```
<div  class = "nav navbar"> 
    <!-- rest of your code -->
</div>
```
Make sure you use **className** instead of **class**. Example

```
<div  className = "nav navbar"> 
    <!-- rest of your code -->
</div>
```

**You only need to create the elements and style the navbar**

This is fairly easy and straightforward to do, please comment on this issue and I'll assign it to you.

**Comment by Padhma** [comment]
Assign this to me

**Comment by ezioda004** [comment]
@Padhma Yes, please go ahead.
Feel free to ask us here or in PM if you get stuck
.
Please try to do it by Saturday morning.

**Comment by seethaR03** [comment]
Is this issue still open?

**Comment by ezioda004** [comment]
Hey @seethaR03,
This issue is assigned to @Padhma, however you can work on [this UI design](https://github.com/UdacityFrontEndScholarship/quiz-app/issues/50) 
We'll be making more issues everyday, so keep an eye out on the issues page.

**Comment by creatorisback** [comment]
If Issue is still not completed i'll be happy to help

**Comment by sb39** [comment]
@ezioda004  commit made against it or still pending ?

**Comment by kadumuri1994** [comment]
@creatorisback , @sb39 . I think the commit has not been made yet. However, @Padhma is working on it. @ezioda004 will let you know today if it can be assigned to you as deadline is today I believe.
