### ISSUE TITLE
Create and Style Welcome page content

### ISSUE THREAD

**Issue by ezioda004** [UdacityFrontEndScholarship/quiz-app#53]
## Create and Style Welcome page content

![image](https://user-images.githubusercontent.com/20020273/39008887-a33dcf54-4427-11e8-98a6-fde344642338.png)

Here are the [images](https://imgur.com/a/AJt6L4o) used.

How to get started? Read our [project setup instructions](https://github.com/UdacityFrontEndScholarship/quiz-app/blob/master/CONTRIBUTING.md#project-setup-instructions).
Fork the project, navigate to directory 
`quiz-app => src => Component => Home => Home.js and Home.css`

You may also need to style the main container component. Its located in 
`quiz-app => src => Component => Welcome Page =>Welcome.css `

You need to do write HTML inside the `<main></main>` element and style inside Page.css
We're using Bootstrap4 for this project but feel free to use native CSS wherever you require.

Note: 
1. If you use any self closing tags such as `<img>`, `<input>`, `<br>`
Make sure you always close them like this `<img />`, `<input />`, `<br />`

2. If you add a `class` to an element example 
```
<div  class = "nav navbar"> 
    <!-- rest of your code -->
</div>
```
Make sure you use **className** instead of **class**. Example

```
<div  className = "nav navbar"> 
    <!-- rest of your code -->
</div>
```

Feel free to ask any question regarding this to us here or over slack.

This is fairly easy and straightforward to do, please comment on this issue and I'll assign it to you.

**Comment by benatbanglr369** [comment]
@ezioda004 I dont see Page => Page.js and Page.css

**Comment by ezioda004** [comment]
@benatbanglr369 My bad, it should be `Home`, fixed it.

**Comment by benatbanglr369** [comment]
"CSS inside the <main></main>" It is HTML or CSS @ezioda004  ?

**Comment by ezioda004** [comment]
@benatbanglr369 Thanks for pointing it out, not my day 😅

**Comment by benatbanglr369** [comment]
Problem is its mid-night :joy:

**Comment by benatbanglr369** [comment]
Can you assign this to me pls?

**Comment by souryavaranasi** [comment]
Hi @ezioda004  Can I work on this issue?

**Comment by ezioda004** [comment]
@souryavaranasi Can you try to do it by tomorrow night? We're trying to speed things up.

**Comment by souryavaranasi** [comment]
@ezioda004  well then, that would be okay for me. will give my best.

**Comment by ezioda004** [comment]
@souryavaranasi Awesome! Assigning to you.
Feel free to message us if you need to any help.

**Comment by goss-gowtham** [comment]
@ezioda004, Can I work on this too?
Or will you be creating more issues, So that I'll work on that?

**Comment by kadumuri1994** [comment]
@goss-gowtham , don't worry. @ezioda004 will be surely creating new issues. Keep a check on issues section
