### ISSUE TITLE
Home Page Horizontal Scroll Bar Issue

### ISSUE THREAD

**Issue by lalitmee** [UdacityFrontEndScholarship/quiz-app#61]
Home page is having a small horizontal Scrollbar. I think it is because of the image on the right(second image). It's looking awkward. 

![peek 2018-04-21 22-59](https://user-images.githubusercontent.com/10762218/39087045-2ff3e08c-45b8-11e8-8e25-2a2981e5cca0.gif)

**Comment by benatbanglr369** [comment]
Could you please assign this Issue to me?

**Comment by ezioda004** [comment]
Assigning to @benatbanglr369 
Please try to do it by today as its not a big one.

**Comment by benatbanglr369** [comment]
Sure!

**Comment by ezioda004** [comment]
#64 
Resolved, closing.
