### ISSUE TITLE
Make a project setup guide with a quick github starter.

### ISSUE THREAD

**Issue by ezioda004** [UdacityFrontEndScholarship/quiz-app#7]

**Comment by lalitmee** [comment]
Hey @ezioda004 , by project setup guide, you mean that how other people can set up this project in their systems or something else?

**Comment by ezioda004** [comment]
@lalitmee Yes, this is what we talked about yesterday. 
Let someone aside from team handle this, since this is easy one and also a good first issue.

**Comment by lilithxxx** [comment]
I am taking this up.

**Comment by lalitmee** [comment]
@lilithxxx, Yeah sure.

**Comment by ezioda004** [comment]
@lilithxxx Please wait till we add a Readme file. 
It's being worked on.

**Comment by abhishekakade** [comment]
I'd like to work on project setup guide too and how to sync the fork if it's okay :)

**Comment by ezioda004** [comment]
@lilithxxx You can work on github starter guide. Step by step instruction, as to how to setup github.
There's a github section in the CONTRIBUTING.md file.

@abhishekakade You can work on project setup guide and common troubleshooting methods such as how to sync your fork. There's "Project Setup Instructions" in the CONTRIBUTING.md file.

Assigning to both of you.

**Comment by lalitmee** [comment]
hey @abhishekakade, for **how to sync your fork**, I think [this](https://help.github.com/articles/syncing-a-fork/) will be a good source of information. If you want any help, tell us. :+1:

**Comment by abhishekakade** [comment]
@ezioda004 sure. Thank you @ezioda004, @lalitmee :)
