### ISSUE TITLE
favicon icon for the website

### ISSUE THREAD

**Issue by jibin2706** [UdacityFrontEndScholarship/quiz-app#78]
![screenshot_2018-05-02_21-35-44](https://user-images.githubusercontent.com/28289448/39535398-70b19adc-4e51-11e8-81ec-8f198e88f3df.png)

**Comment by ezioda004** [comment]
@jibin2706 Any changes are you proposing?

**Comment by jibin2706** [comment]
@kadumuri1994 I'm talking about the icon near the title.

**Comment by abhishekakade** [comment]
@jibin2706, you mean favicon?

**Comment by seethaR03** [comment]
Is this open?

**Comment by Logan1x** [comment]
Do you have any ideas in mind for favicon? @seethaR03

**Comment by lalitmee** [comment]
I think we need to design a favicon for our project if we really want to add that in our web application. We would need some creative ideas for designing the favicon. :innocent: 

If anyone has any idea, you are welcome with your ideas for sharing and discussing about that which one will be better to have. :+1:

**Comment by seethaR03** [comment]
Is this alright or something more creative is required ?
![favicon](https://user-images.githubusercontent.com/27719165/39545674-91fe474e-4e6f-11e8-94dd-6df2dcb11d73.gif)

**Comment by lalitmee** [comment]
Hey @seethaR03, I think its good but it should not blink and if content can be made more visible, that would be better.

**Comment by seethaR03** [comment]
No need of animation in the icon!?Shall I come up with another and make a PR then?

**Comment by seethaR03** [comment]
![favicon-_1_](https://user-images.githubusercontent.com/27719165/39558860-c2dae9cc-4eaf-11e8-8607-b2d4982d128f.gif)
How about this one ?

**Comment by nehavatsyan** [comment]
![ss](https://user-images.githubusercontent.com/35574268/39564727-05b4d762-4ed3-11e8-90ed-10e2873973f8.png)
how about this one i have created two

**Comment by jibin2706** [comment]
I think the design should be similar to the logo.

**Comment by lalitmee** [comment]
Yeah, favicon should be similar to the logo but I think it should describe something about the application. Because we cant have the full logo or title in the favicon. :innocent:

**Comment by seethaR03** [comment]
What about the latest one I have posted @lalitmee @jibin2706

**Comment by lalitmee** [comment]
Hey @seethaR03, @nehavatsyan and all others who are suggesting for the favicon icon. I would like to show you the favicon icon of [gmail](https://www.google.com/a/cpanel/iiitvadodara.ac.in/images/favicon.ico), I think we can follow the measurements according to this and for the design, we will try to integrate all of your designs into one.

**Comment by seethaR03** [comment]
Alright @lalitmee  but you are saying full title should not be mentioned in logo?

**Comment by jibin2706** [comment]
@lalitmee the fonts can use the blue pink color from the logo

**Comment by Logan1x** [comment]
>you are saying full title should not be mentioned in the icon

the favicon should represent what is our website/project is all about does not matter if it contains text or not.

**Comment by nehavatsyan** [comment]
![favicon](https://user-images.githubusercontent.com/35574268/39589924-1e6cfaba-4f1d-11e8-9915-0f268f54844e.png)
i tried a new one is it okay

**Comment by Logan1x** [comment]
@nehavatsyan  it is not much visible in 16 x 16

**Comment by nehavatsyan** [comment]
ya i will fix its size

**Comment by Logan1x** [comment]
the design is most likely decided by voting I think

**Comment by seethaR03** [comment]
![9860favicon-_1_](https://user-images.githubusercontent.com/27719165/39591951-fbfb4ea4-4f22-11e8-8841-713a1af009e3.gif)
@lalitmee  is it better now ?

**Comment by lalitmee** [comment]
@seethaR03, yeah it's better now. Let's wait for others what the say about this. :innocent:

**Comment by sumilmehta** [comment]
![skill up](https://user-images.githubusercontent.com/18137211/39672229-b9925670-5143-11e8-9d30-5c392eaf7b95.png)

**Comment by vikkrantxx7** [comment]
How's this - 
![target-circle-blue-64](https://user-images.githubusercontent.com/37444378/39795405-83dff538-536d-11e8-81e4-0312e8e91b66.png)

**Comment by vattytrivedi** [comment]
# First logo
![skillup](https://user-images.githubusercontent.com/14287645/39796594-01cbd528-5375-11e8-8343-cb8032ee93ab.jpg)
# Second logo
![skillup-2](https://user-images.githubusercontent.com/14287645/39796595-02319bc4-5375-11e8-9e57-3fa2b0bf659c.jpg)

**Comment by Logan1x** [comment]
@vattytrivedi  it would be great if you could paste images with 16 x 16 size.

**Comment by vattytrivedi** [comment]
Here are the requested file @Logan1x. Sorry I shared the drive link because cannot upload ico files.

[Logo 1](https://drive.google.com/file/d/1T9_78drK33JcFstet7qsnM6wcssVT_4M/view?usp=sharing)
[Logo 2](https://drive.google.com/file/d/1rh0uDLL-_iC4MQyFMOhRKpPIzZpaaWi1/view?usp=sharing)

**Comment by Logan1x** [comment]
Then you should share a screenshot of the title bar with favicon.ico in it. @vattytrivedi . 

btw my vote is for the 1st one(but idk how it'll look in 16x16).

**Comment by vattytrivedi** [comment]
Here is the Screenshot.
![ss-skill](https://user-images.githubusercontent.com/14287645/39803006-488a5bde-538d-11e8-9de2-99e0c03d7d98.png)

**Comment by jibin2706** [comment]
@vattytrivedi The second one looks good

**Comment by Vanisha27** [comment]
@vattytrivedi I like the second one :ok_hand:

**Comment by abhishekakade** [comment]
![favicons-all](https://user-images.githubusercontent.com/26276153/39824663-845715fe-53cd-11e8-9bbd-ce0e138fb310.png)

**Comment by abhishekakade** [comment]
![facicons-all-firefox](https://user-images.githubusercontent.com/26276153/39825274-09d7ffbc-53cf-11e8-8951-285dc8e8f24c.JPG)
![favicons-all-chrome](https://user-images.githubusercontent.com/26276153/39825275-0a0da568-53cf-11e8-9264-576f4030adc4.JPG)

**Comment by vattytrivedi** [comment]
Is favicon still pending to be decided?

**Comment by jibin2706** [comment]
@ezioda004 less the 2 days left

**Comment by Vanisha27** [comment]
We're going with the one submitted by @vattytrivedi :smiley: 

![](https://user-images.githubusercontent.com/14287645/39796595-02319bc4-5375-11e8-9e57-3fa2b0bf659c.jpg)
Thank you @vattytrivedi @abhishekakade @sumilmehta @vikkrantxx7 @seethaR03 @nehavatsyan for your time and effort. We truly appreciate it. :innocent:

**Comment by vattytrivedi** [comment]
Do I have to make a PR for the favicon?
@Vanisha27

**Comment by Vanisha27** [comment]
Yes, please make a PR. @vattytrivedi

**Comment by vattytrivedi** [comment]
@Vanisha27 
Instead of PR here is the link to the ico. You can download it and add to the repo.
https://drive.google.com/file/d/1hk8yCCinx2T9bBLgOZBBBqbgS1GJShBZ/view?usp=sharing
