### ISSUE TITLE
Update the Header for Dashboard

### ISSUE THREAD

**Issue by ezioda004** [UdacityFrontEndScholarship/quiz-app#85]
Implement the navbar as shown in this image.
![image](https://user-images.githubusercontent.com/20020273/39674799-0e54ea80-516f-11e8-9164-62d0d7a1cd23.png)

You'll be making changes in Header.js/Header.css
Head down to `quiz-app => src => Components => Header => Header.js/Header.css

**Important instructions to follow before you start working because this requires you to be authenticated and added to the database.**

Step 1. In the project directory, open terminal and do `npm install`
Step 2. Now do `npm install -g nodemon`
Step 3. Run `nodemon server/server.js`
Step 4. Open another terminal window in the same directory (DO NOT close the other one)
Step 5. Run `npm start`

You'll see that webpack has opened the frontend server at `http://localhost:3000`, open another tab and type `http://localhost:5000`, this is port where the server is running.

Step 6. Now, open open the link `https://localhost:3000/auth/google` which will authenticate you and add your basic information to the database.
Step 7 Now head to `https://localhost:3000/dashboard` , you should be able to see your google profile image here.
This is where you'll see the changes you'll be making.
  
In the `Header` Component, you should see a `switch` statement. You'll need to write JSX ie HTML inside the `return` statement. Bootstrap4 is already imported so need to worry about that as well.

Please comment on this issue and I'll assign it to you.

**Comment by Padhma** [comment]
Can I work on this issue @ezioda004 ???

**Comment by ezioda004** [comment]
@Padhma Yes, please go ahead.
Feel free to DM us on slack or ask here if you're stuck in any of the steps or require any sort of assistance.
